//
// Created by Donato Wolfisberg on 12.12.2017.
//

#ifndef GUIV2_COLOR_H
#define GUIV2_COLOR_H

using namespace std;

#include <windows.h>


enum GUI_COLOR {
	GUI_COLOR_FOREGROUND_WHITE = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED,
	GUI_COLOR_FOREGROUND_BLACK = 0x0,
	GUI_COLOR_FOREGROUND_BLUE = FOREGROUND_BLUE,
	GUI_COLOR_FOREGROUND_GREEN = FOREGROUND_GREEN,
	GUI_COLOR_FOREGROUND_RED = FOREGROUND_RED,

	GUI_COLOR_BACKGROUND_WHITE = BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_RED,
	GUI_COLOR_BACKGROUND_BLACK = 0x0,
	GUI_COLOR_BACKGROUND_BLUE = BACKGROUND_BLUE,
	GUI_COLOR_BACKGROUND_GREEN = BACKGROUND_GREEN,
	GUI_COLOR_BACKGROUND_RED = BACKGROUND_RED,
};


void setGuiColor(GUI_COLOR foreground, GUI_COLOR background);

void resetGuiColor();

GUI_COLOR getDefaultForegroundColor();

GUI_COLOR getDefaultBackgroundColor();


#endif //GUIV2_COLOR_H
